thedevopsguy-rails/config/routes.rb
Rails.application.routes.draw do
  resources :albums
  # devise_scope :user do
  #   get "/signin" => "devise/sessions#new", as: "new_user_session" # custom path to login/sign_in
  #   get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end  

  # devise_for :users, :controllers => { :registrations => 'registrations' }, 
  #                     :path => 'accounts', 
  #                     :path_names =>{ :sign_in => 'login', 
  #                                     :sign_up => 'new', 
  #                                     :sign_out => 'logout', 
  #                                     :password => 'secret', 
  #                                     :confirmation => 'verification' }

  devise_scope :user do
    get "/signin" => "devise/sessions#new", as: "new_new_user_session"
    get "/signup" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  


  resources :interactions do
    collection do
      post 'upvote' => 'interactions#upvote'
      post 'downvote' => 'interactions#downvote'
    end
  end
  resources :article_idol_records
  resources :idols
  resources :article_model_records
  resources :models
  resources :images
  resources :videos
  resources :article_tag_records
  resources :tags
  resources :vehicles do
    match '/scrape', to: 'vehicles#scrape', via: :post, on: :collection
  end
  
  
  ActiveAdmin.routes(self)
  resources :students
  namespace :admin_lte do
    resources :users
    resources :articles
    resources :inventory_items
    resources :inventory_item_categories
    resources :inventory_items
    resources :specific_items
    get '/home' => 'application#home'
    # Admin root
    root to: 'application#index'
  end

  # get '/admin' => 'static_pages#home'
  
  resources :articles, param: :slug
  resources :orders
  resources :order_line_items
  
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  get '/gallery' => 'static_pages#gallery'
  get '/bmi' => 'static_pages#bmi'
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  get '/donate' => 'static_pages#donate'
  post '/interactions/create' => 'interactions#create', :via => :interactions
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

thedevopsguy-rails/app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :inventory_item, required: false
  belongs_to :order, required: false
  before_save :save_total_price 
  	

  #accepts_nested_attributes_for :order
  #validates :order_item_qty, presence: true, numericality: { only_integer: true, greater_than: 0 }
  def total_fixed_price
    fixed_item_price.to_i * order_item_qty.to_i
  end
private
  def updated_total_price
    inventory_item.price.to_i * order_item_qty.to_i
  end 

  def save_total_price
    self.total_price = inventory_item.price.to_f * order_item_qty.to_f
  end

end

thedevopsguy-rails/app/controllers/order_line_items_controller.rb
class OrderLineItemsController < ApplicationController
  include CurrentOrder
  before_action :set_order_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_order, only: [:create]
  before_action :authenticate_user!, except: [:show,:create] 

  # GET /order_line_items
  # GET /order_line_items.json
  def index
    @order_line_items = OrderLineItem.all
  end

  # GET /order_line_items/1
  # GET /order_line_items/1.json
  def show
  end

  # GET /order_line_items/new
  def new
    @order_line_item = OrderLineItem.new
  end

  # GET /order_line_items/1/edit
  def edit
  end

  # POST /order_line_items
  # POST /order_line_items.json
  def create
    #order = current_order
    #@order_line_item = OrderLineItem.new(order_line_item_params)
    #@order.save
    #session[:order_id] = @order.id
    inventory_item = InventoryItem.find(params[:inventory_item_id])
    
    if inventory_item.quantity == nil || inventory_item.quantity <= 0
      redirect_to home_path, notice: 'not enough.' 
    else
      
      @order_line_item = @order.add_inventory_item(inventory_item)
      #binding.pry

      inventory_item.quantity = inventory_item.quantity - 1
      inventory_item.save
      #@order_line_item = OrderLineItem.new(order_line_item_params)
      respond_to do |format|
        if @order_line_item.save
          format.html { redirect_to @order_line_item.order, notice: 'Order line item was successfully created.' }
          format.js
          format.json { render :show, status: :created, location: @order_line_item }
        else
          format.html { render :new }
          format.json { render json: @order_line_item.errors, status: :unprocessable_entity }
        end
      end
    end
    #binding.pry
  end

  # PATCH/PUT /order_line_items/1
  # PATCH/PUT /order_line_items/1.json
  def update
    #@order = current_order
    #@order_line_item = @order.order_line_items.find(params[:id])
    #@order_line_item.update_attributes(order_item_params)
    # binding.pry

    respond_to do |format|
      if @order_line_item.update(order_line_item_params)
        format.html { redirect_to @order_line_item.order, notice: 'Order line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line_item }
      else
        format.html { render :edit }
        format.json { render json: @order_line_item.errors, status: :unprocessable_entity }
      end
    end

    #@order_line_items = @order.order_line_items
  end

  # DELETE /order_line_items/1
  # DELETE /order_line_items/1.json
  def destroy
    #@order = current_order
    #@order_line_item = @order.order_line_items.find(params[:id])
    #@order_line_item.destroy
    #@order_line_items = @order.order_line_items    
    #binding.pry
    @inventory_item = @order_line_item.inventory_item
    @inventory_item.quantity = @inventory_item.quantity + @order_line_item.order_item_qty
    @inventory_item.save
    @order_line_item.destroy
    respond_to do |format|
      format.html { redirect_to home_url, notice: 'Order line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line_item
      @order_line_item = OrderLineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_item_params
      params.require(:order_line_item).permit(:inventory_item_id, :order_id, :order_item_qty, :total_price, :order_line_item_price, :fixed_item_price)
    end
end

thedevopsguy-rails/app/helpers/order_line_items_helper.rb
module OrderLineItemsHelper
end

thedevopsguy-rails/app/views/order_line_items/_form.html.erb
<%= form_with(model: order_line_item, local: true) do |form| %>
  <% if order_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_line_item.errors.count, "error") %> prohibited this order_line_item from being saved:</h2>

      <ul>
      <% order_line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :inventory_item_id %>
    <%= form.text_field :inventory_item_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :order_item_qty %>
    <%= form.number_field :order_item_qty %>
  </div>

  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price %>
  </div>

  <div class="field">
    <%= form.label :order_line_item_price %>
    <%= form.text_field :order_line_item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

thedevopsguy-rails/app/views/order_line_items/create.js.erb
$('#cart').html("<%= @order.order_line_items.sum(:order_item_qty) %>");
$('#item_qnt-<%= @order_line_item.inventory_item_id %>').html("<%= InventoryItem.find(@order_line_item.inventory_item_id).quantity %>");


thedevopsguy-rails/app/views/order_line_items/edit.html.haml
- if current_user && current_user.admin?
  %h1 Editing Order Line Item
  = render 'form', order_line_item: @order_line_item
  = link_to 'Show', @order_line_item
  |
  = link_to 'Back', order_line_items_path

thedevopsguy-rails/app/views/order_line_items/index.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %h1 Order Line Items
  %table
    %thead
      %tr
        %th Inventory item
        %th Order
        %th Order item qty
        %th Total price
        %th Order line item price
        %th(colspan="3")
    %tbody
      - @order_line_items.each do |order_line_item|
        %tr
          %td= order_line_item.inventory_item.id
          %td= order_line_item.order.id
          %td= order_line_item.order_item_qty
          %td= order_line_item.total_price
          %td= order_line_item.order_line_item_price
          %td= link_to 'Show', order_line_item
          %td= link_to 'Edit', edit_order_line_item_path(order_line_item)
          %td= link_to 'Destroy', order_line_item, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Order Line Item', new_order_line_item_path
-else
  %div

thedevopsguy-rails/app/views/order_line_items/new.html.erb
<h1>New Order Line Item</h1>

<%= render 'form', order_line_item: @order_line_item %>

<%= link_to 'Back', order_line_items_path %>

thedevopsguy-rails/app/views/order_line_items/show.html.haml
- if current_user && current_user.admin?
  %p#notice= notice
  %p
    %strong Inventory item:
    = @order_line_item.inventory_item.id
  %p
    %strong Order:
    = @order_line_item.order.id
  %p
    %strong Order item qty:
    = @order_line_item.order_item_qty
  %p
    %strong Total price:
    = @order_line_item.total_price
  %p
    %strong Order line item price:
    = @order_line_item.order_line_item_price
  = link_to 'Edit', edit_order_line_item_path(@order_line_item)
  |
  = link_to 'Back', order_line_items_path