thedevopsguy-rails/config/routes.rb
Rails.application.routes.draw do
  resources :albums
  # devise_scope :user do
  #   get "/signin" => "devise/sessions#new", as: "new_user_session" # custom path to login/sign_in
  #   get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end  

  # devise_for :users, :controllers => { :registrations => 'registrations' }, 
  #                     :path => 'accounts', 
  #                     :path_names =>{ :sign_in => 'login', 
  #                                     :sign_up => 'new', 
  #                                     :sign_out => 'logout', 
  #                                     :password => 'secret', 
  #                                     :confirmation => 'verification' }

  devise_scope :user do
    get "/signin" => "devise/sessions#new", as: "new_new_user_session"
    get "/signup" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  


  resources :interactions do
    collection do
      post 'upvote' => 'interactions#upvote'
      post 'downvote' => 'interactions#downvote'
    end
  end
  resources :article_idol_records
  resources :idols
  resources :article_model_records
  resources :models
  resources :images
  resources :videos
  resources :article_tag_records
  resources :tags
  resources :vehicles do
    match '/scrape', to: 'vehicles#scrape', via: :post, on: :collection
  end
  
  
  ActiveAdmin.routes(self)
  resources :students
  namespace :admin_lte do
    resources :users
    resources :articles
    resources :inventory_items
    resources :inventory_item_categories
    resources :inventory_items
    resources :specific_items
    get '/home' => 'application#home'
    # Admin root
    root to: 'application#index'
  end

  # get '/admin' => 'static_pages#home'
  
  resources :articles, param: :slug
  resources :orders
  resources :order_line_items
  
  resources :users
  resources :inventory_items
  resources :inventory_models
  resources :inventory_item_categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  get '/gallery' => 'static_pages#gallery'
  get '/bmi' => 'static_pages#bmi'
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about_us' => 'static_pages#about_us'
  get '/contact' => 'static_pages#contact'
  get '/shopping_cart' => 'static_pages#shopping_cart'
  get '/categories' => 'inventory_item_categories#index'
  get '/checkout' => 'static_pages#checkout'
  get '/donate' => 'static_pages#donate'
  post '/interactions/create' => 'interactions#create', :via => :interactions
  #get '/articles' => 'static_pages#articles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

thedevopsguy-rails/app/models/idol.rb
class Idol < ApplicationRecord
    has_one :image
    has_many :article_idol_records
    has_many :articles, :through => :article_idol_records
    
    include PgSearch
    pg_search_scope :search_by_full_name, against: [:name]
end

thedevopsguy-rails/app/controllers/idols_controller.rb
class IdolsController < InheritedResources::Base
  before_action :set_idol, only: [:show, :edit, :update, :destroy]
  # GET /idols
  # GET /idols.json
  def index
    # if params[:name]
    #   @idols = Idol.search_by_full_name(params[:name]).page(params[:page])
    # else
    #   @idols = Idol.all.page(params[:page])
    # end

    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @idols = Idol.where("name LIKE ?", "%#{@name}%").page(params[:page])
    else
      @idols = Idol.all.page(params[:page])
    end
    
  end

  # GET /idols/1
  # GET /idols/1.json
  def show
    set_meta_tags title: @idol.name,
      description: 'Show the page in single.',
      keywords: 'Site, single, Page, Show'
      # @video_tags = Tag.joins(:article_tag_records).where( "article_tag_records.article_id" => @article.id).uniq
      @idols_articles = @idol.articles
  end

  # GET /idols/new
  def new
    @idol = Idol.new
  end

  # GET /idols/1/edit
  def edit
  end

  # POST /idols
  # POST /idols.json
  def create
    @idol = Idol.new(idol_params)

    respond_to do |format|
      if @idol.save
        format.html { redirect_to @idol, notice: 'Idol was successfully created.' }
        format.json { render :show, status: :created, location: @idol }
      else
        format.html { render :new }
        format.json { render json: @idol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idols/1
  # PATCH/PUT /idols/1.json
  def update
    respond_to do |format|
      if @idol.update(idol_params)
        format.html { redirect_to @idol, notice: 'Idol was successfully updated.' }
        format.json { render :show, status: :ok, location: @idol }
      else
        format.html { render :edit }
        format.json { render json: @idol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idols/1
  # DELETE /idols/1.json
  def destroy
    @idol.destroy
    respond_to do |format|
      format.html { redirect_to idols_url, notice: 'Idol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_idol
      @idol = Idol.find(params[:id])
    end

    def idol_params
      params.require(:idol).permit(:alias, :country, :city, :astrological, :birthday, :debutyear, :haircolor, :eyecolor, :height, :measurement, :tattoos, :piercings, :piercing)
    end
end

thedevopsguy-rails/app/helpers/idols_helper.rb
module IdolsHelper
end

thedevopsguy-rails/app/views/idols/_form.html.slim
= simple_form_for(@idol) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :alias
    = f.input :country
    = f.input :city
    = f.input :astrological
    = f.input :birthday
    = f.input :debut-year
    = f.input :hair-color
    = f.input :eye-color
    = f.input :height
    = f.input :measurement
    = f.input :tattoos
    = f.input :piercings

  .form-actions
    = f.button :submit

thedevopsguy-rails/app/views/idols/bak.index.html.slim
h1 Listing idols

table
  thead
    tr
      th Alias
      th Country
      th City
      th Astrological
      th Birthday
      th Debut-year
      th Hair-color
      th Eye-color
      th Height
      th Measurement
      th Tattoos
      th Piercings
      th
      th
      th

  tbody
    - @idols.each do |idol|
      tr
        td = idol.alias
        td = idol.country
        td = idol.city
        td = idol.astrological
        td = idol.birthday
        td = idol.debut-year
        td = idol.hair-color
        td = idol.eye-color
        td = idol.height
        td = idol.measurement
        td = idol.tattoos
        td = idol.piercings
        td = link_to 'Show', idol
        td = link_to 'Edit', edit_idol_path(idol)
        td = link_to 'Destroy', idol, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Idol', new_idol_path

thedevopsguy-rails/app/views/idols/bak.show.html.slim
/ p#notice = notice

/ p
/   strong Alias:
/   = @idol.alias
/ p
/   strong Country:
/   = @idol.country
/ p
/   strong City:
/   = @idol.city
/ p
/   strong Astrological:
/   = @idol.astrological
/ p
/   strong Birthday:
/   = @idol.birthday
/ p
/   strong Debut-year:
/   = @idol.debut-year
/ p
/   strong Hair-color:
/   = @idol.hair-color
/ p
/   strong Eye-color:
/   = @idol.eye-color
/ p
/   strong Height:
/   = @idol.height
/ p
/   strong Measurement:
/   = @idol.measurement
/ p
/   strong Tattoos:
/   = @idol.tattoos
/ p
/   strong Piercings:
/   = @idol.piercings

/ => link_to 'Edit', edit_idol_path(@idol)
/ '|
/ =< link_to 'Back', idols_path

thedevopsguy-rails/app/views/idols/edit.html.slim
h1 Editing idol

== render 'form'

=> link_to 'Show', @idol
'|
=< link_to 'Back', idols_path

thedevopsguy-rails/app/views/idols/index.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %h1 Inventory Item Categories
  %table
    %thead
      %tr
        %th Category name
        %th(colspan="3")
    %tbody
      - @idols.each do |idol|
        %tr
          %td= idol.name
          %td= link_to 'Show', idol
          %td= link_to 'Edit', edit_idol_path(idol)
          %td= link_to 'Destroy', idol, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Inventory Item Category', new_idol_path
- else
  .card(style = "margin: 0px 0px;")
    .card-header.idol-intro
      .row.idol-info        
        .col-12.idol-search
          = simple_form_for :search, url: idols_path, method: "GET", html: { class: 'form form-inline my-lg-0 p-2 flex-fill bd-highlight d-flex justify-content-center' } do |f|
            = f.input :name, input_html: {value: ""}, label: false, placeholder: 'Search idols name...'
            -# = f.submit "S", :class => "btn btn-danger"
            = button_tag type: 'submit', class: "button btn btn-danger" do
              %i.fa.fa-dot-circle-o(aria-hidden="true")
                         
              
              
          -# = form_tag idols_path, method: :get do
          -#   = text_field_tag 'name', params[:name], placeholder: "Enter user's name or surname"
          -#   = submit_tag 'Search!'
    .card-body      
      .row
        - @idols.each do |idol| 
          .card.col-sm-6.col-lg-3.col-12.border-0.mb-5.idol-thumb            
            = image_tag ( idol.image.url ), :class => "img-fluid card-img", alt: "idol images"
            .text-center.overlay
              .idols-info
                .text-center.idol-name
                  %h4
                    =idol.name
                .text-center.idol-button
                  = link_to 'Explore', idol, class: 'btn btn-outline-danger btn-lg'
      .paging-part
        = paginate @idols      

thedevopsguy-rails/app/views/idols/new.html.slim
h1 New idol

== render 'form'

= link_to 'Back', idols_path

thedevopsguy-rails/app/views/idols/show.html.haml
- if user_signed_in? && current_user.admin
  %p#notice= notice
  %p
    %strong Name:
    = @idol.name
  %p
    %strong Description:
    = @idol.description
  %p
    %strong Content:
    = @idol.content
  = link_to 'Edit', edit_idol_path(@idol)
  |
  = link_to 'Back', idols_path
  %br
  = link_to 'New Article', new_idol_path
- else
- content_for :head do
  = tag :meta, property: "og:name", content: @idol.name
  -# = tag :meta, property: "og:description", content: @product.description
  -# = tag :meta, property: "og:url", content: request.url
  -# = tag :meta, property: "og:image", content: @product.image
  -# = tag :meta, property: "og:image:width", content: 1200
  -# = tag :meta, property: "og:image:height", content: 630   
.col.idol-show-container
  .row.idol-bio
    .col-4.idol-image
      = image_tag (@idol.image.url), :class => "img-fluid",alt: "idol images"
    .col-8.idol-info
      .row.idol-name
        %h1
          = @idol.name
      .row.idol-description
        %p
          If she isn’t shooting a new nasty video this Japanese angel can be found playing with something.

  .row.separator.text-center
    .col-2
      .running-line-left
      
    .col-8.idol-video-count
      %h5
        Her latest videos -         
        = @idols_articles.count
        
    .col-2.running-line-right
      -# runing line
  .row.idol-videos
    - @idols_articles.each do |article|
      = render 'shared/article_container' , article: article    
    -# .col-3.col-sm-6